import funk

# Вводимо ім'я стовбця
#funk.parsing("B")
#funk.parsing("C")
#funk.parsing("D")
#funk.parsing("E")
#funk.parsing("F")
#funk.parsing("G")
funk.parsing("H")
#funk.parsing("I")
#funk.parsing("J")
#funk.parsing("K")
#funk.parsing("L")
#funk.parsing("M")
#funk.parsing("N")
#funk.parsing("O")
#funk.parsing("P")
#funk.parsing("Q")
#funk.parsing("R")
#funk.parsing("S")
#funk.parsing("T")
#funk.parsing("U")
#funk.parsing("V")
#funk.parsing("W")
#funk.parsing("X")
#funk.parsing("Y")
#funk.parsing("Z")